## Analysis options for this project
# See: https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

# Customize or disable lints from flutter_lints below.
linter:
  rules:
    # Example: disable avoid_print if you want to allow prints during development
    # avoid_print: false
